{% set name = "azure-mgmt-containerinstance" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-containerinstance-{{ version }}.zip
  sha256: deb125554bdb1aa17df69a596a7514af0146b420176a4db384c54e77a9fd6e46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.0,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure.mgmt.containerinstance
    - azure.mgmt.containerinstance.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Container Instance Client Library for Python
  description: |
    This is the Microsoft Azure Container Instance Client Library.

    Azure Resource Manager (ARM) is the next generation of management APIs that
    replace the old Azure Service Management (ASM).
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://docs.microsoft.com/en-us/azure/developer/python/

extra:
  recipe-maintainers:
    - xylar
